/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_elevoc_voicefrontandroid_MainActivity */

#ifndef _Included_com_elevoc_voicefrontandroid_MainActivity
#define _Included_com_elevoc_voicefrontandroid_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_elevoc_voicefrontandroid_MainActivity
 * Method:    start_process
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_elevoc_voicefrontandroid_MainActivity_start_1process
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
